### ISSUE TITLE
该插件好像并没有起到分页的作用

### ISSUE THREAD

**Issue by jackey-jiang** [aly8246/collection-util#1]
结合mybatis plus 使用, 控制台 是 打印了  collectionUtil active!   但好像并没有处理分页,  条数仍然不对,请问  是不是还需要设置什么东西

**Comment by aly8246** [comment]
你好请加我qq 1558146696我帮你看看，这个项目我太久没用了有点忘记了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"江易疯先森"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月20日(星期五) 下午2:28
收件人:&nbsp;"aly8246/collection-util"<collection-util@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[aly8246/collection-util] 该插件好像并没有起到分页的作用 (#1)





 
结合mybatis plus 使用, 控制台 是 打印了  collectionUtil active!   但好像并没有处理分页,  条数仍然不对,请问  是不是还需要设置什么东西

**Comment by aly8246** [comment]
https://blog.csdn.net/qq_35425243/article/details/101562553
附上csdn博客，应该能解决问题，README里面不是很明确
因为这个插件要和pagehelper共存，分工解决，所以还需要对mapper有一定的改造才能使用

**Comment by jackey-jiang** [comment]
ok的, 已经加了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "gols"<notifications@github.com&gt;; 
发送时间: 2020年3月20日(星期五) 下午2:30
收件人: "aly8246/collection-util"<collection-util@noreply.github.com&gt;; 
抄送: "基本无解"<327156719@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [aly8246/collection-util] 该插件好像并没有起到分页的作用 (#1)





 你好请加我qq 1558146696我帮你看看，这个项目我太久没用了有点忘记了 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"江易疯先森"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年3月20日(星期五) 下午2:28 
 收件人:&amp;nbsp;"aly8246/collection-util"<collection-util@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;[aly8246/collection-util] 该插件好像并没有起到分页的作用 (#1) 
 
 
 
 
 
   
 结合mybatis plus 使用, 控制台 是 打印了  collectionUtil active!   但好像并没有处理分页,  条数仍然不对,请问  是不是还需要设置什么东西
